### ISSUE TITLE
Size of GPT2

### ISSUE THREAD

**Issue by mchen644** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#11]
Hello, sorry to bother again.
I want to find out which size of GPT2 can you obtain the experiment result? I've found out there are several sizes with the largest one being 1.5B? And can you offer the approximate occupation of GPU memory when finetuning?
Thank you if you can solve my puzzle!

**Comment by PSacfc** [comment]
We use the pre-trained GPT2 model with size of 117M and 12 transformer layers. We use a single V100 with memory of 32GB. The batch size for GPT-2 can be set up to 1024, as we split the data into individual channels.

**Comment by mchen644** [comment]
> We use the pre-trained GPT2 model with size of 117M and 12 transformer layers. We use a single V100 with memory of 32GB. The batch size for GPT-2 can be set up to 1024, as we split the data into individual channels.

"12 transformer layers", is it the default setting for gpt2 with size 117M or is it a hyperparameter you set for the experiment? By the way, the task I am focusing is long term forcasting.

**Comment by PSacfc** [comment]
It is the pre-trained model file we used. And we only use the first 6 layers with pre-trained parameters for long term forecasting.

**Comment by mchen644** [comment]
> It is the pre-trained model file we used. And we only use the first 6 layers with pre-trained parameters for long term forecasting.

Got it, thank you for your replying!
