### ISSUE TITLE
Only loading 1 channel for long term forecasting?

### ISSUE THREAD

**Issue by Hank0626** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#15]
https://github.com/DAMO-DI-ML/NeurIPS2023-One-Fits-All/blob/eec04e1d286f1c55d58935d532d0fcf7ce0f2c97/Long-term_Forecasting/data_provider/data_loader.py#L94-L102

In line 101 and 102, you only select 1 channels for `seq_x`, how do you predict multi-variate time series? I think feat_id is always 0, so you only select the first channel.

@tianzhou2011

**Comment by csguoh** [comment]
I also have the same question, could the authors reply to this?

**Comment by GGchen1997** [comment]
How about this issue?

**Comment by PSacfc** [comment]
There will be insufficient for traffic dataset with gpt2. All channels are stretched into only 
 one, the same idea with channel independence.
