### ISSUE TITLE
Do you use multiple V100 when batch_size=2024

### ISSUE THREAD

**Issue by MogicianXD** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#19]
As mentioned in [issue-11](https://github.com/DAMO-DI-ML/NeurIPS2023-One-Fits-All/issues/11#issuecomment-1835524907), you use a single V100 with memory of 32GB. However, I found it out-of-memory in long-term forecasting on Electricity and Traffic datasets, of which your scripts set the batch size to 2048.

Could you provide the maximum GPU occupation in README? I think it would be better to help the followers. Thanks!

**Comment by PSacfc** [comment]
When using a batch size of 2048, you will need 4 V100 GPUs. If using a single GPU, you can adjust the batch size to 512. Thank you for your suggestion, we will update this information in the readme later.

**Comment by MogicianXD** [comment]
Thanks for your advice!
