### ISSUE TITLE
请问哪个是你们提出的模型呢？是GPT4TS么？我看到论文里面写的是GPT2或者FPT

### ISSUE THREAD

**Issue by yi-zhi111** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#2]

**Comment by tianzhou2011** [comment]
[GPT4TS](https://github.com/DAMO-DI-ML/NeurIPS2023-One-Fits-All/blob/main/Long-term_Forecasting/models/GPT4TS.py)

**Comment by Rusullhu** [comment]
这里的4应该是for 的意思
