### ISSUE TITLE
[Bug] Please Check your requirements.txt

### ISSUE THREAD

**Issue by issaccv** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#4]
The last two package versions given in requirements：
```
torch==1.8.1
transformers==4.30.1
```
Well, the `transformer==4.30.1` requires `pytorch>=1.9,!=1.12.0`

Can you dump a conda env into a yaml file or just update requirements.txt.

😊

**Comment by tianzhou2011** [comment]
This conflict is inconsequential. We employ torch 1.81 and transformer 4.30.1. While the conflict may affect certain features in transformer 4.30.1, it does not impact the specific part that we utilize. But using torch version 1.9 would likely be acceptable.
