### ISSUE TITLE
cannot reproduce the imputation results on ettm1

### ISSUE THREAD

**Issue by Leanna97** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#44]
Thank you very much for your outstanding work. 

We download your codes and run the imputation task on the ETTm1 dataset using the provided script, but we are unable to reproduce the results from the paper. When mask_rate=0.5, the MSE we obtained is 0.196, whereas the MSE in the paper is 0.040. Could you please explain why this discrepancy occurs? 

Thank you very much.

**Comment by tianzhou2011** [comment]
#23

**Comment by Leanna97** [comment]
Thanks! We obtain the expected results.
