### ISSUE TITLE
In anomaly detection, why do we segment x_enc into subsequences with seg_num=25 before normalization, instead of directly normalizing the entire sequence of x_enc?

### ISSUE THREAD

**Issue by ZhoumingLiu** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#49]
![efb072c12a5a18217e846ed442aae8b](https://github.com/user-attachments/assets/838b6a18-5a34-42bf-afb4-c5f23a3697b8)
Hello, Author. I have two questions to ask you: 
1. Why do we segment x_enc into subsequences with seg_num=25 before normalization, instead of directly normalizing the entire sequence of x_enc? 
2. Why is the value of seg_num set to 25? If I apply this to my own dataset, should I also set it to 25?

**Comment by tianzhou2011** [comment]
Normalization should take into account both local and global information. If a sequence starts with a large value followed by smaller ones, local normalization is much more effective. The value of 25 is merely a reference point we use to achieve reasonable results; feel free to adjust this parameter to suit your specific context.

**Comment by ZhoumingLiu** [comment]
Thank you for your prompt response; it has been very helpful to me.
