### ISSUE TITLE
Haven't seen the use of DataEmbedding in GPT4TS

### ISSUE THREAD

**Issue by mchen644** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#8]
Hello, I got a question when looking for the source code that there isn't seen to have used the DataEmbedding(TokenEmbedding+PositionalEmbedding+TemporalEmbedding) in GPT4TS.py(though there contains 'import'  module of DataEmbedding), can you please clarify if the Data Embedding is used? Is this module important? Thank you!

**Comment by PSacfc** [comment]
GPT2 has positional encoding module, thus we only utilize a linear projection to project the input time series to the required dimension. We didn't make a detailed comparison on temporal embedding but you can add it by making some modifications.
