### ISSUE TITLE
GPT layers used of Imputation task 

### ISSUE THREAD

**Issue by Wang-XingHao** [DAMO-DI-ML/NeurIPS2023-One-Fits-All#9]
First of all, thanks for your great work and sorry for opening this without content at first by mistake.
I've seen the scripts in Imputation task all use 6 GPT layers, while it's optimal to use 3 layers as the paper mentioned, so is there any small mistakes? or could you please provide the results using 6layers ?
And there's another small issue I may need a little help, it seems huggingface.co is blocked in some areas, so I downloaded  GPT-2 in https://huggingface.co/gpt2/tree/main , could you please help check if it's the same version as you guys used?

**Comment by PSacfc** [comment]
We used 3 layers GPT2 in the imputation task.

**Comment by Wang-XingHao** [comment]
sorry for opening this issue without right edition, could you please check my small issues again?

**Comment by PSacfc** [comment]
Thank for your reminder! We have modified the scripts. When I first used GPT-2, it was downloadable and the link you mentioned should be the same version we used.

**Comment by Wang-XingHao** [comment]
Thanks for your kind reply, best wishes!
